version: '3'
services:
  jupyter:
    image: jupyter/base-notebook
    restart: always
    command: "jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - '8888:8888'
    volumes:
      - ./:/root
    working_dir: /root